/* config.h - Generated by CMake from cmake/config.h.cmake */
#ifndef CONFIG_H
#define CONFIG_H

/* Package information */
#define PACKAGE "libgpod"
#define PACKAGE_NAME "libgpod"
#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define PACKAGE_STRING "libgpod @PROJECT_VERSION@"
#define VERSION "@PROJECT_VERSION@"

/* Gettext package — required by glib's gi18n-lib.h / _() macro */
#define GETTEXT_PACKAGE "libgpod"

/* Feature flags */
#cmakedefine HAVE_ZLIB 1
#cmakedefine HAVE_LIBXML 1
#cmakedefine HAVE_GDKPIXBUF 1

/* Platform checks */
#cmakedefine HAVE_LOCALTIME_R 1
#cmakedefine HAVE_STRUCT_TM_TM_GMTOFF 1

/* Permanently disabled features */
/* #undef HAVE_HAL */
/* #undef HAVE_LIBIMOBILEDEVICE */
/* #undef HAVE_SGUTILS */
/* #undef HAVE_LIBUSB */
/* #undef HAVE_PYGOBJECT */

/* Enable POSIX/platform extensions */
#ifndef _GNU_SOURCE
#define _GNU_SOURCE 1
#endif
#ifdef __APPLE__
#ifndef _DARWIN_C_SOURCE
#define _DARWIN_C_SOURCE 1
#endif
#endif

#endif /* CONFIG_H */
